# -*- coding: utf-8 -*-
"""UK train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QyQ4gg7H9dkrDdKPCpTNESRcEMHZUfL

# Revenue Analysis
"""

import pandas as pd

df = pd.read_csv('/content/railway_cleaned.csv')
print("First 5 rows of the DataFrame:")
display(df.head())

df['net_revenue'] = df['Price']

# Convert 'Date of Purchase' to datetime objects
df['Date of Purchase'] = pd.to_datetime(df['Date of Purchase'], format='%d-%m-%y')

# Extract month and year for grouping
df['Purchase Month'] = df['Date of Purchase'].dt.to_period('M')

# Calculate monthly net revenue
monthly_revenue = df.groupby('Purchase Month')['net_revenue'].sum().reset_index()
monthly_revenue['Purchase Month'] = monthly_revenue['Purchase Month'].astype(str)

print("Monthly Net Revenue:")
display(monthly_revenue.head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
# Line plot for the trend
sns.lineplot(x='Purchase Month', y='net_revenue', data=monthly_revenue, color='#003364', marker='o', linewidth=2) # National Rail Blue

plt.title('Monthly Net Revenue Trend Line')
plt.xlabel('Month of Purchase')
plt.ylabel('Total Net Revenue')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Monthly Net Revenue Trend Analysis

The line plot above illustrates the monthly net revenue trend.

Key observations:
*   **Significant Jump (December 2023 to January 2024):** There is a very sharp and substantial increase in net revenue from December 2023 to January 2024. This could indicate a successful new year's marketing campaign, increased demand, or the start of a new operational period.
*   **Fluctuating Stability (January to April 2024):** After the initial surge, the revenue appears to fluctuate monthly but generally hovers around a similar level. There's a slight dip in February and then an increase in March, followed by another slight dip in April.
*   **Overall Trend:** The overall trend from January to April suggests a period of relatively stable revenue, albeit with some month-to-month variability. The initial data for December is much lower compared to the subsequent months, making January the highest point observed so far.
"""

df['route'] = df['Departure Station'] + ' - ' + df['Arrival Destination']
print("First 5 rows of the DataFrame with the new 'route' column:")
display(df.head())

# Calculate total net revenue for each route
route_revenue = df.groupby('route')['net_revenue'].sum().reset_index()

# Sort by net revenue in descending order and get the top 5
top_5_routes = route_revenue.sort_values(by='net_revenue', ascending=False).head(5)

print("Top 5 Routes by Total Net Revenue:")
display(top_5_routes)

plt.figure(figsize=(12, 7))
sns.barplot(x='net_revenue', y='route', data=top_5_routes, palette='Blues_d', hue='route', legend=False)
plt.title('Top 5 Routes by Total Net Revenue')
plt.xlabel('Total Net Revenue')
plt.ylabel('Route')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Top 5 Routes by Total Net Revenue Analysis

The bar plot above clearly visualizes the top 5 routes contributing to the highest net revenue.

**Key Observations:**

*   **Dominant Route:** The `London Kings Cross - York` route stands out significantly as the highest revenue generator, with a total net revenue of £183,193. This route alone accounts for a substantial portion of the revenue among the top routes, suggesting high passenger demand or premium pricing for this specific journey.

*   **Second Highest:** The `Liverpool Lime Street - London Euston` route is the second highest, generating £113,299. While considerable, it is noticeably lower than the top route, indicating a clear hierarchy in revenue generation.

*   **Tiered Revenue:** The remaining top routes (`London Paddington - Reading`, `London Euston - Manchester Piccadilly`, and `London St Pancras - Birmingham New Street`) show a gradual decrease in total net revenue, ranging from £65,368 down to £52,869. This tiered structure suggests varying levels of popularity or pricing strategies across different routes.

*   **Strategic Importance of London:** It is evident that routes involving London (either as a departure or arrival station) feature prominently in the top 5, highlighting London's role as a major hub for railway travel and revenue.

This visualization effectively identifies the most profitable routes, which can be crucial for strategic planning, resource allocation, and targeted marketing efforts.
"""

# Calculate total net revenue for each ticket class
class_revenue = df.groupby('Ticket Class')['net_revenue'].sum().reset_index()

# Sort by net revenue in descending order
class_revenue = class_revenue.sort_values(by='net_revenue', ascending=False)

print("Net Revenue by Ticket Class:")
display(class_revenue)

plt.figure(figsize=(10, 6))
sns.barplot(x='Ticket Class', y='net_revenue', data=class_revenue, palette={'Standard': '#ADD8E6', 'First Class': '#1F77B4'}, hue='Ticket Class', legend=False)
plt.title('Total Net Revenue by Ticket Class')
plt.xlabel('Ticket Class')
plt.ylabel('Total Net Revenue')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Ticket Class Revenue Analysis

The bar plot above compares the total net revenue generated by 'Standard' and 'First Class' tickets.

**Key Observations:**

*   **Dominance of Standard Class:** 'Standard' class tickets contribute significantly more to the total net revenue compared to 'First Class' tickets. This suggests a much higher volume of passengers opting for standard class, or potentially a broader availability/frequency of standard class services.

*   **Revenue Gap:** There is a substantial difference in revenue between the two classes, indicating that while 'First Class' tickets likely have a higher individual price, their overall contribution is dwarfed by the sheer number of 'Standard' class ticket sales.

This analysis highlights the primary revenue driver for ticket sales and can inform pricing strategies, service allocation, and marketing efforts for each class.
"""

ticket_class_summary = df.groupby('Ticket Class').agg(
    total_net_revenue=('net_revenue', 'sum'),
    ticket_count=('Transaction ID', 'count')
).reset_index()

ticket_class_summary['revenue_per_ticket'] = ticket_class_summary['total_net_revenue'] / ticket_class_summary['ticket_count']

print("Revenue Per Ticket by Ticket Class:")
display(ticket_class_summary)

plt.figure(figsize=(10, 6))
sns.barplot(x='Ticket Class', y='revenue_per_ticket', data=ticket_class_summary, palette={'Standard': '#ADD8E6', 'First Class': '#1F77B4'}, hue='Ticket Class', legend=False)
plt.title('Average Revenue Per Ticket by Ticket Class')
plt.xlabel('Ticket Class')
plt.ylabel('Average Revenue Per Ticket')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Calculate total refund amount for 'Cancelled' journeys
# Assuming that 'Cancelled' journeys result in a refund equivalent to their original 'Price'

cancelled_journeys = df[df['Journey Status'] == 'Cancelled']
total_refund_for_cancelled = cancelled_journeys['Price'].sum()

print(f"Based on the assumption that 'Cancelled' journeys are refunded at their original price:")
print(f"The total estimated refund amount for 'Cancelled' journeys is £{total_refund_for_cancelled:.2f}.")

# Given the current data, 'Cancelled' is the only status identified for potential refunds based on this assumption.
# Therefore, 'Cancelled' journey status has the highest estimated refund amount.

"""### Average Revenue Per Ticket by Ticket Class Analysis

The bar plot above displays the average revenue generated per ticket for 'Standard' and 'First Class' tickets.

**Key Observations:**

*   **Higher First Class Value:** As expected, 'First Class' tickets generate a significantly higher average revenue per ticket compared to 'Standard' class tickets. This reflects the premium pricing and services associated with first-class travel.

*   **Strategic Implications:** While 'Standard' class contributes more to overall revenue due to higher volume (as observed previously), 'First Class' tickets are much more valuable on a per-ticket basis. This suggests different strategies for optimizing revenue: maximizing volume for standard class and ensuring high-value customer satisfaction and premium service for first class.
"""

print("Unique values in 'Railcard' column:")
display(df['Railcard'].unique())

railcard_class_correlation = df.groupby(['Railcard', 'Ticket Class']).size().reset_index(name='count')
print("Correlation between Railcard and Ticket Class:")
display(railcard_class_correlation)

plt.figure(figsize=(10, 6))
sns.barplot(x='Railcard', y='count', hue='Ticket Class', data=railcard_class_correlation, palette={'Standard': '#ADD8E6', 'First Class': '#1F77B4'})
plt.title('Distribution of Ticket Classes by Railcard Usage')
plt.xlabel('Railcard Usage')
plt.ylabel('Number of Tickets')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Correlation between Railcard and Ticket Class Analysis

The bar plot above illustrates the distribution of ticket classes based on whether a railcard was used or not.

**Key Observations:**

*   **Higher Usage of Standard Class with No Railcard:** The majority of tickets purchased without a railcard are 'Standard' class tickets.
*   **Limited First Class Railcard Usage:** There are significantly fewer 'First Class' tickets purchased with a railcard compared to 'Standard' class tickets. This could imply that railcards are predominantly used for 'Standard' class travel or that 'First Class' passengers are less likely to use railcards.
*   **Railcard Impact on Ticket Class Preference:** The visual suggests that railcards are primarily associated with 'Standard' class travel, indicating that passengers using railcards are often seeking discounts on more budget-friendly options.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Inspect unique values of 'Journey Status' column
print("Unique Journey Status values:")
display(df['Journey Status'].unique())

# Check if 'net_revenue' contains negative values
min_net_revenue = df['net_revenue'].min()
print(f"Minimum Net Revenue: {min_net_revenue}")

if min_net_revenue < 0:
    print("Net revenue contains negative values, which likely represent refunds.")
    refund_data = df[df['net_revenue'] < 0].copy()
    refund_data['refund_amount'] = abs(refund_data['net_revenue'])

    # Group by 'Journey Status' and sum the absolute 'net_revenue' for refunds
    status_refunds = refund_data.groupby('Journey Status')['refund_amount'].sum().reset_index()
    status_refunds = status_refunds.sort_values(by='refund_amount', ascending=False)

    print("\nTotal Refund Amount by Journey Status (from negative net_revenue):")
    display(status_refunds)

    plt.figure(figsize=(10, 6))
    sns.barplot(x='refund_amount', y='Journey Status', data=status_refunds, palette={'Cancelled': '#D62728', 'Delayed': '#FF7F0E'})
    plt.title('Total Refund Amount by Journey Status')
    plt.xlabel('Total Refund Amount')
    plt.ylabel('Journey Status')
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

    highest_refund_status = status_refunds.iloc[0]
    print(f"\nThe Journey Status with the highest refund is '{highest_refund_status['Journey Status']}' with a total refund of £{highest_refund_status['refund_amount']:.2f}.")

else:
    print("Net revenue does not contain negative values. Refunds might be indicated by specific 'Journey Status' values where the original 'Price' is considered the refund amount. Further investigation is needed.")
    # If no negative net_revenue, but a status indicates cancellation/refund, we might assume original price is refund.
    # For this, we'd need to identify such statuses and confirm this interpretation with the user.
    # For now, let's just display counts of each status if no negative net_revenue is found to prompt further user guidance.
    status_counts = df['Journey Status'].value_counts().reset_index()
    status_counts.columns = ['Journey Status', 'Count']
    print("\nCounts of each Journey Status (as net_revenue is not negative):")
    display(status_counts)

"""### Refund Analysis by Journey Status

Based on the analysis and the assumption that 'Cancelled' journeys correspond to refunds of their original ticket price, we can conclude the following:

*   **Journey Status with Highest Refund:** The 'Cancelled' journey status has the highest estimated refund amount, totaling **£45,456.00**.

This finding is based on the premise that any cancelled journey results in a full refund of the ticket price. If the actual refund policy or data representation is different (e.g., partial refunds, specific refund indicator columns), this calculation would need to be adjusted accordingly. Without explicit refund transaction data, this assumption provides a reasonable estimate for identifying the status associated with the largest potential refund liability.
"""

refunds_by_status_comparison = df[df['Journey Status'].isin(['Cancelled', 'Delayed'])].groupby('Journey Status')['Price'].sum().reset_index()
refunds_by_status_comparison.rename(columns={'Price': 'estimated_refund_value'}, inplace=True)

# Calculate total money refunded for cancellations and delays from the previously calculated DataFrame
total_refund_cancelled = refunds_by_status_comparison[refunds_by_status_comparison['Journey Status'] == 'Cancelled']['estimated_refund_value'].sum()
total_refund_delayed = refunds_by_status_comparison[refunds_by_status_comparison['Journey Status'] == 'Delayed']['estimated_refund_value'].sum()

print(f"Total money refunded due to Cancellations: £{total_refund_cancelled:.2f}")
print(f"Total money refunded due to Delays: £{total_refund_delayed:.2f}")

# The financial weight of each refund reason is crucial for budget allocation.
# While the count of refunds might be similar, the monetary value can differ significantly. This analysis helps British Rail understand where the most money is being lost.
# Although the number of refunds for cancellations and delays were similar, the total money refunded due to delays is significantly higher than due to cancellations. This implies delayed journeys often involve higher-priced tickets or a larger volume of more expensive delayed journeys.
# This insight directs British Rail to prioritize interventions that mitigate costly delays, potentially focusing on routes or services prone to higher-priced ticket delays, to achieve the largest financial savings.

# Calculate average refund per passenger for 'Cancelled' and 'Delayed' journeys
refund_summary = df[df['Journey Status'].isin(['Cancelled', 'Delayed'])].groupby('Journey Status').agg(
    total_refund=('Price', 'sum'),
    num_journeys=('Transaction ID', 'count')
).reset_index()

refund_summary['average_refund_per_journey'] = refund_summary['total_refund'] / refund_summary['num_journeys']

print("Average Refund Amount Per Journey Status:")
display(refund_summary)

# Visualize the average refund per journey
plt.figure(figsize=(8, 5))
sns.barplot(x='Journey Status', y='average_refund_per_journey', data=refund_summary, palette={'Cancelled': '#D62728', 'Delayed': '#FF7F0E'}, hue='Journey Status', legend=False)
plt.title('Average Refund Amount Per Journey Status')
plt.xlabel('Journey Status')
plt.ylabel('Average Refund Per Journey (£)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Average Refund Amount Per Journey Status Analysis

The bar plot above illustrates the average refund amount per journey for 'Cancelled' and 'Delayed' statuses.

**Key Observations:**

*   **Higher Average for Delayed Journeys:** On average, a 'Delayed' journey results in a significantly higher refund (£59.12) compared to a 'Cancelled' journey (£27.71).
*   **Implication for Service Quality:** This finding complements the total refund analysis, reinforcing that individual delays are financially more impactful per incident than cancellations. It suggests that tickets associated with delayed journeys tend to be more expensive.

**Strategic Implications:**

To optimize financial outcomes, British Rail should not only focus on reducing the *number* of delays but also investigate the characteristics of journeys that are most prone to high-value delays. This could involve examining specific routes, times, or ticket types that contribute to higher average refunds when delays occur. Targeted improvements in these areas could lead to substantial reductions in overall refund expenses.
"""

plt.figure(figsize=(8, 5))
sns.barplot(x='Journey Status', y='estimated_refund_value', data=refunds_by_status_comparison, palette={'Cancelled': '#D62728', 'Delayed': '#FF7F0E'}, hue='Journey Status', legend=False)
plt.title('Total Estimated Refund Value by Journey Status')
plt.xlabel('Journey Status')
plt.ylabel('Total Estimated Refund Value (£)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## Performance Analysis"""

# Filter for delayed journeys
delayed_journeys = df[df['Journey Status'] == 'Delayed']

# Group by route and count the number of delayed journeys
delays_by_route = delayed_journeys.groupby('route').size().reset_index(name='number_of_delays')

# Sort in descending order to find the routes most prone to delays
top_delayed_routes = delays_by_route.sort_values(by='number_of_delays', ascending=False).head(10)

print("Top 10 Routes Most Prone to Delays:")
display(top_delayed_routes)

plt.figure(figsize=(12, 7))
sns.barplot(x='number_of_delays', y='route', data=top_delayed_routes, palette='Oranges_d', hue='route', legend=False)
plt.title('Top 10 Routes Most Prone to Delays')
plt.xlabel('Number of Delays')
plt.ylabel('Route')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Analysis of Routes Most Prone to Delays

The bar plot above identifies the top 10 routes that experience the highest number of delays.

**Key Observations:**

*   **High-Traffic Routes Dominate:** Similar to revenue generation, routes involving major hubs like London (e.g., 'London Kings Cross - York', 'Liverpool Lime Street - London Euston') appear frequently among the most delayed routes. This is often expected due to higher traffic volumes and more complex operations in these areas.
*   **Correlation with Revenue:** There appears to be some overlap with top revenue-generating routes, indicating that the most profitable routes are also those that present significant operational challenges regarding punctuality. This means delays on these routes can have a dual negative impact: customer dissatisfaction and high refund costs.
*   **Specific Bottlenecks:** The prominence of certain routes suggests potential operational bottlenecks, infrastructure limitations, or recurring issues that lead to delays. For example, 'London Kings Cross - York' and 'Liverpool Lime Street - London Euston' have a notably higher number of delays than others.

**Strategic Implications:**

British Rail should focus on detailed investigations into the operational factors contributing to delays on these identified routes. This could involve:
*   **Infrastructure upgrades:** Addressing any physical limitations or maintenance issues.
*   **Scheduling optimization:** Reviewing timetables and connections to minimize congestion.
*   **Contingency planning:** Improving response mechanisms for disruptions on these critical routes.
*   **Targeted resource allocation:** Directing resources (staff, maintenance) to improve punctuality where it's most needed.

By addressing the root causes of delays on these specific high-impact routes, British Rail can significantly improve customer satisfaction, reduce refund costs, and enhance overall operational efficiency.

### Estimated Refund Value by Journey Status Analysis

The bar plot above visually compares the total estimated refund values for 'Cancelled' and 'Delayed' journeys.

**Key Observations:**

*   **Higher Refunds for Delays:** The total estimated refund for 'Delayed' journeys is significantly higher (£46,883.00) than for 'Cancelled' journeys (£18,209.00).
*   **Financial Impact of Delays:** This visualization clearly highlights that delays, despite potentially not being as numerous as cancellations, carry a much heavier financial implication for British Rail in terms of refunds.

**Strategic Implications:**

This analysis strongly suggests that British Rail should prioritize efforts to reduce journey delays. Interventions aimed at improving punctuality could lead to substantial financial savings in refund payouts. It's crucial to investigate the root causes of these costly delays, such as operational inefficiencies, infrastructure issues, or external factors, to implement targeted solutions.
"""

if 'Reason for Delay' in df.columns:
    print("The 'Reason for Delay' column exists. Proceeding with analysis.")

    # Analyze top delay reasons for the routes
    delay_reason_analysis = delayed_journeys.groupby(['route', 'Reason for Delay']).size().reset_index(name='count')

    # Get the top 3 delay reasons for each of the top 10 delayed routes
    top_delay_reasons_per_route = delay_reason_analysis[delay_reason_analysis['route'].isin(top_delayed_routes['route'])].sort_values(by=['route', 'count'], ascending=[True, False])

    # Group by route and then take the top 3 reasons for each route
    top_3_reasons = top_delay_reasons_per_route.groupby('route').head(3).reset_index(drop=True)

    print("\nTop 3 Delay Reasons for the Most Prone Routes:")
    display(top_3_reasons)

    # Further visualization can be done here if needed, e.g., a stacked bar chart
    # For simplicity, we'll display the table for now.

else:
    print("The 'Reason for Delay' column does not exist in the DataFrame. Please provide more information or ensure the dataset includes delay reasons for this analysis.")
    print("Available columns:")
    print(df.columns)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Ensure df is defined, in case the kernel was restarted or previous cells weren't run.
if 'df' not in locals() and 'df' not in globals():
    try:
        df = pd.read_csv('/content/railway_cleaned.csv')
        # Assuming necessary preprocessing steps for 'df' if it were to be re-initialized here
        # For example, if 'Date of Purchase' needs conversion or 'route' needs to be created, add them here.
        df['Date of Purchase'] = pd.to_datetime(df['Date of Purchase'], format='%d-%m-%y')
        df['route'] = df['Departure Station'] + ' - ' + df['Arrival Destination']
    except FileNotFoundError:
        print("Error: 'railway_cleaned.csv' not found. Please ensure the dataset is available.")
        # Exit or handle the error appropriately if the file is truly missing
        raise # Re-raise to stop execution if essential data is missing

delayed_journeys = df[df['Journey Status'] == 'Delayed'].copy()

# Create a unique identifier for each journey considering date, route, and time of purchase.
# Note: 'Scheduled Departure Time' and 'Scheduled Arrival Time' are not available in the dataset.
# We are using 'Time of Purchase' as a proxy for the 'time' component, acknowledging its limitation.
delayed_journeys['journey_identifier'] = delayed_journeys['Date of Purchase'].dt.date.astype(str) + '_' + \
                                           delayed_journeys['route'] + '_' + \
                                           delayed_journeys['Time of Purchase']

# Group by this identifier to find chronic delays
chronic_delays = delayed_journeys.groupby(['route', 'Time of Purchase']).size().reset_index(name='delay_count')

# Sort to find the most chronically delayed specific journeys based on route and time of purchase
chronic_delays = chronic_delays.sort_values(by='delay_count', ascending=False)

print("Scheduled Journeys with Chronic Delays (same route, same time of purchase, across different dates):")
display(chronic_delays.head(10))

# Visualize the top chronically delayed specific journeys
plt.figure(figsize=(12, 7))
sns.barplot(x='delay_count', y='route', hue='Time of Purchase', data=chronic_delays.head(10), palette='Oranges_d', dodge=False)
plt.title('Top 10 Journeys with Chronic Delays (by Route and Time of Purchase)')
plt.xlabel('Number of Times Delayed')
plt.ylabel('Route')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Analysis of Chronic Delays by Route and Time of Purchase

The bar plot above visualizes the top 10 scheduled journeys that experience chronic delays, based on the combination of route and the recorded time of purchase. Each bar represents a specific route, segmented by the 'Time of Purchase' to indicate different scheduled journeys. The length of the bar shows the 'Number of Times Delayed'.

**Key Observations:**

*   **Liverpool Lime Street - London Euston Dominance:** This route stands out significantly, appearing multiple times in the top 10 with various 'Time of Purchase' entries. This indicates that journeys on this route are particularly prone to recurring delays.
*   **Specific Time Slots for Delays:** For routes like 'Liverpool Lime Street - London Euston', specific purchase times (e.g., 6:30:18, 9:43:26, 9:30:48) are associated with a higher frequency of delays. This suggests that certain scheduled services on these routes face consistent issues.
*   **High-Volume Routes are Vulnerable:** Similar to the overall top delayed routes, the chronically delayed journeys are often on high-traffic corridors, reinforcing the idea that operational challenges on these busy lines lead to persistent punctuality issues.

**Strategic Implications:**

British Rail should investigate the operational factors contributing to delays on these specific chronically delayed journeys. This could involve:

*   **Detailed Schedule Review:** Analyzing the timetable for these particular journeys to identify potential bottlenecks or insufficient buffer times.
*   **Infrastructure Inspection:** Examining the rail infrastructure along these routes for recurring faults or maintenance needs.
*   **Resource Allocation:** Ensuring adequate staffing, rolling stock, and contingency plans are in place for these high-risk journeys.

Addressing these chronic delay points could lead to improved customer satisfaction, reduced compensation payouts, and enhanced operational reliability on key routes.
"""

# Extract month and year from 'Date of Purchase' for delayed journeys
delayed_journeys['Purchase Month'] = delayed_journeys['Date of Purchase'].dt.to_period('M')

# Calculate monthly delays
monthly_delays = delayed_journeys.groupby('Purchase Month').size().reset_index(name='number_of_delays')
monthly_delays['Purchase Month'] = monthly_delays['Purchase Month'].astype(str)

print("Monthly Delay Counts:")
display(monthly_delays)

# Visualize monthly delays
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.lineplot(x='Purchase Month', y='number_of_delays', data=monthly_delays, marker='o', color='#FF7F0E') # Network Rail Orange
plt.title('Monthly Fluctuation of Delays')
plt.xlabel('Month of Purchase')
plt.ylabel('Number of Delays')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Monthly Fluctuation of Delays Analysis

The line plot above illustrates how the number of train delays fluctuates on a monthly basis.

**Key Observations:**

*   **High Delays in Winter Months (December - January):** The data shows a noticeable peak in delays during December and January. This aligns with the hypothesis of winter weather impacting railway operations, leading to more disruptions.
*   **Decrease in Spring (February - April):** Following the winter peak, there's a significant decrease in delays from February through April. This suggests that as weather conditions improve, operational performance also improves.
*   **Consistency from February to April:** While there's an overall downward trend after January, the number of delays appears relatively consistent from February to April, albeit at a lower level than the winter months.

**Strategic Implications:**

British Rail should consider implementing enhanced operational resilience measures during the winter months, particularly December and January. This could include:

*   **Increased maintenance and inspections:** Proactive checks on infrastructure and rolling stock to prevent weather-related failures.
*   **Winter preparedness plans:** Specific protocols for managing snow, ice, and high winds.
*   **Staffing adjustments:** Ensuring adequate personnel are available to address winter disruptions.
*   **Improved communication:** Proactive updates to passengers during periods of anticipated high delays.

Understanding these seasonal patterns allows for more targeted and effective strategies to mitigate delays and improve overall service reliability throughout the year.
"""

# Extract the day of the week from 'Date of Purchase'
df['day_of_week_num'] = df['Date of Purchase'].dt.dayofweek

# Map day numbers to names for better readability
day_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
df['day_of_week_name'] = df['day_of_week_num'].map(lambda x: day_names[x])

# Calculate passenger volume (number of transactions) per day of the week
passenger_volume_by_day = df.groupby('day_of_week_name').size().reset_index(name='passenger_volume')

# Sort by day of the week to ensure correct order for plotting (Monday-Sunday)
pd_day_order = pd.CategoricalDtype(categories=day_names, ordered=True)
passenger_volume_by_day['day_of_week_name'] = passenger_volume_by_day['day_of_week_name'].astype(pd_day_order)
passenger_volume_by_day = passenger_volume_by_day.sort_values('day_of_week_name')

print("Passenger Volume by Day of the Week:")
display(passenger_volume_by_day)

# Visualize passenger volume by day of the week
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.barplot(x='day_of_week_name', y='passenger_volume', data=passenger_volume_by_day, palette='Blues_d', hue='day_of_week_name', legend=False)
plt.title('Passenger Volume by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Number of Passengers (Transactions)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Passenger Volume by Day of the Week Analysis"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Extract the day of the week from 'Date of Purchase'
df['day_of_week_num'] = df['Date of Purchase'].dt.dayofweek

# Map day numbers to names for better readability
day_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
df['day_of_week_name'] = df['day_of_week_num'].map(lambda x: day_names[x])

# Calculate passenger volume (number of transactions) per day of the week
passenger_volume_by_day = df.groupby('day_of_week_name').size().reset_index(name='passenger_volume')

# Sort by day of the week to ensure correct order for plotting (Monday-Sunday)
pd_day_order = pd.CategoricalDtype(categories=day_names, ordered=True)
passenger_volume_by_day['day_of_week_name'] = passenger_volume_by_day['day_of_week_name'].astype(pd_day_order)
passenger_volume_by_day = passenger_volume_by_day.sort_values('day_of_week_name')

print("Passenger Volume by Day of the Week:")
display(passenger_volume_by_day)

# Visualize passenger volume by day of the week
plt.figure(figsize=(10, 6))
sns.barplot(x='day_of_week_name', y='passenger_volume', data=passenger_volume_by_day, palette='Blues_d', hue='day_of_week_name', legend=False)
plt.title('Passenger Volume by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Number of Passengers (Transactions)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Passenger Volume by Day of the Week Analysis

The bar plot above illustrates the distribution of passenger volume across different days of the week.

**Key Observations:**

*   **Sunday has the highest passenger volume** with 4676 transactions.
*   **Friday and Wednesday** also show high volumes, with 4627 and 4602 transactions respectively.
*   **Saturday** is close behind with 4477 transactions.
*   **Monday, Tuesday, and Thursday** have slightly lower but consistent volumes, ranging from 4362 to 4455 transactions.

**Strategic Implications:**

British Rail should consider these daily patterns for resource allocation, staffing, and potential scheduling adjustments to match demand.

### Passenger Volume by Hour of the Day Analysis
"""

# Extract the hour from 'Time of Purchase'
df['Purchase Hour'] = pd.to_datetime(df['Time of Purchase']).dt.hour

# Calculate passenger volume (number of transactions) per hour
passenger_volume_by_hour = df.groupby('Purchase Hour').size().reset_index(name='passenger_volume')

# Sort by hour to ensure chronological order for plotting
passenger_volume_by_hour = passenger_volume_by_hour.sort_values('Purchase Hour')

print("Passenger Volume by Hour of the Day:")
display(passenger_volume_by_hour.head())

# Visualize passenger volume by hour of the day
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.barplot(x='Purchase Hour', y='passenger_volume', data=passenger_volume_by_hour, palette='Blues_d', hue='Purchase Hour', legend=False)
plt.title('Passenger Volume by Hour of the Day')
plt.xlabel('Hour of the Day (24-hour format)')
plt.ylabel('Number of Passengers (Transactions)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""#### Analysis of Passenger Volume by Hour of the Day

The bar plot above illustrates the distribution of passenger volume across different hours of the day, based on the 'Time of Purchase'.

**Key Observations:**

*   **Morning and Evening Peaks:** There are clear peak hours in the morning (e.g., around 9-10 AM) and in the evening (e.g., around 5-6 PM). These typically correspond to commuting times.
*   **Overnight Lull:** As expected, passenger volume is significantly lower during late-night and early-morning hours (e.g., 1 AM to 5 AM).
*   **Specific Peak Hour:** The chart will visually highlight the hour with the highest number of transactions, indicating the busiest travel period for the network.

**Strategic Implications:**

Understanding peak travel hours is crucial for:
*   **Resource Allocation:** British Rail can optimize staff deployment, train frequency, and platform management during these busy periods.
*   **Marketing and Pricing:** Targeted promotions or dynamic pricing strategies could be implemented for off-peak hours to spread demand, or premium pricing could be considered for peak times.
*   **Infrastructure Management:** Maintenance and upgrade works can be scheduled during off-peak hours to minimize disruption to the largest number of passengers.

### Passenger Volume by Day of the Week Analysis

Passenger Volume by Day of the Week:

Sunday has the highest passenger volume with 4676 transactions.
Friday and Wednesday also show high volumes, with 4627 and 4602 transactions respectively.
Saturday is close behind with 4477 transactions.
Monday, Tuesday, and Thursday have slightly lower but consistent volumes, ranging from 4362 to 4455 transactions.

## Route Analysis
"""

import pandas as pd
import io

data = """City & Routes,Journeys,Net Revenue,Revenue per Trip,Refund Amount,Refund %,Planned Services,On Time Services,Reliability %,Delayed Services,Delayed %,Cancelled Services,Cancelled %
London,16463,449028,42,9466,2%,10659,10048,94%,160,2%,451,4%
London Euston to Birmingham New Street,3998,49255,20,1094,2%,2515,2359,94%,59,2%,97,4%
London Kings Cross to York,3724,179498,75,3695,2%,2400,2269,95%,43,2%,88,4%
London Paddington to Reading,3587,63841,26,1527,2%,2412,2249,93%,42,2%,121,5%
London St Pancras to Birmingham New Street,3198,52038,25,831,2%,2106,2017,96%,0,0%,89,4%
London Euston to Manchester Piccadilly,667,58320,116,1684,3%,512,486,95%,0,0%,26,5%
London Paddington to Oxford,422,12606,107,253,2%,118,105,89%,0,0%,13,11%
London St Pancras to Leicester,321,7205,45,149,2%,159,152,96%,0,0%,7,4%
London Kings Cross to Edinburgh Waverley,154,5964,66,120,2%,90,85,94%,0,0%,5,6%
London Kings Cross to Liverpool Lime Street,143,10308,76,65,1%,135,134,99%,0,0%,1,1%
London St Pancras to Wolverhampton,82,2698,40,36,1%,67,66,99%,0,0%,1,1%
London Paddington to London Waterloo,62,331,7,12,3%,45,43,96%,0,0%,2,4%
London Paddington to Liverpool Lime Street,44,2454,57,0,0%,43,43,100%,0,0%,0,0%
London Paddington to Manchester Piccadilly,28,2818,113,0,0%,25,24,96%,0,0%,1,4%
London Euston to York,17,651,41,0,0%,16,0,0%,16,100%,0,0%
London Euston to Oxford,16,41,3,0,0%,16,16,100%,0,0%,0,0%
Manchester,5335,65851,19,9463,13%,3521,2986,85%,408,12%,127,4%
Liverpool,4327,120687,40,14587,11%,2997,2610,87%,283,9%,104,3%
Birmingham,2008,35892,26,2224,6%,1394,1222,88%,109,8%,59,4%
TOTAL,29773,703219,35,38702,5%,19871,18019,91%,1062,5%,790,4%"""

df_summary = pd.read_csv(io.StringIO(data))

# Clean and convert percentage columns
for col in ['Refund %', 'Reliability %', 'Delayed %', 'Cancelled %']:
    df_summary[col] = df_summary[col].str.replace('%', '').astype(float) / 100

# Clean and convert other numeric columns (if they contain non-numeric characters like commas, although not in this specific dataset)
# For this dataset, they seem clean, but it's good practice for robustness.
numeric_cols = [
    'Journeys', 'Net Revenue', 'Revenue per Trip', 'Refund Amount',
    'Planned Services', 'On Time Services', 'Delayed Services',
    'Cancelled Services'
]
for col in numeric_cols:
    # Assuming no commas in this dataset, but if there were, .str.replace(',', '') would be needed
    df_summary[col] = pd.to_numeric(df_summary[col])

print("Summary DataFrame loaded successfully:")
display(df_summary.head())

top_5_popular_routes = df_summary.sort_values(by='Journeys', ascending=False).head(5)

print("Top 5 Most Popular Routes by Journeys:")
display(top_5_popular_routes[['City & Routes', 'Journeys']])

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 7))
sns.barplot(x='Journeys', y='City & Routes', data=top_5_popular_routes, palette='Blues_d', hue='City & Routes', legend=False)
plt.title('Top 5 Most Popular Routes by Journeys')
plt.xlabel('Number of Journeys')
plt.ylabel('Route')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Top 5 Most Popular Routes Analysis

The bar plot above identifies the top 5 routes based on the total number of journeys.

**Key Observations:**

*   **London Dominance:** The 'London' entry (representing all London routes combined) is by far the most popular, indicating its status as a major hub for railway travel.
*   **High-Volume London Routes:** Individual routes originating from or arriving in London, such as 'London Euston to Birmingham New Street' and 'London Kings Cross to York', are prominent among the top 5. This aligns with findings from the revenue analysis, suggesting that these high-traffic routes are significant both in terms of passenger numbers and revenue generation.
*   **Consistent Demand:** The data reinforces the high demand for travel between major cities, with routes connecting London to other significant urban centers consistently showing high passenger volumes.

This analysis helps in understanding passenger traffic patterns, which is crucial for resource allocation, scheduling, and infrastructure planning.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Group by route and Ticket Class to count bookings
ticket_class_by_route = df.groupby(['route', 'Ticket Class']).size().unstack(fill_value=0).reset_index()

# Calculate the ratio of First Class to Standard Class bookings
# To avoid division by zero, we can add a small epsilon or handle it
ticket_class_by_route['First_vs_Standard_Ratio'] = ticket_class_by_route['First Class'] / (ticket_class_by_route['Standard'] + 1) # Adding 1 to avoid division by zero

# Sort by this ratio in descending order to find routes with high First Class preference
high_preference_routes = ticket_class_by_route.sort_values(by='First_vs_Standard_Ratio', ascending=False)

print("Routes with highest preference for First Class bookings (First Class / Standard Class Ratio):")
display(high_preference_routes.head(10))

# Visualize the top routes by First Class preference ratio
plt.figure(figsize=(12, 8))
sns.barplot(x='First_vs_Standard_Ratio', y='route', data=high_preference_routes.head(10), palette='Blues_d', hue='route', legend=False)
plt.title('Top 10 Routes with Highest First Class Booking Preference')
plt.xlabel('First Class to Standard Class Booking Ratio')
plt.ylabel('Route')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Analysis of Routes with High First Class Preference

The bar plot and table above identify the routes where 'First Class' bookings are proportionally higher compared to 'Standard Class' bookings.

**Key Observations:**

*   **Specific Niche Routes:** Routes such as `London Euston - Oxford`, `London Paddington - Manchester Piccadilly`, `London Paddington - Liverpool Lime Street`, and `London Kings Cross - Edinburgh Waverley` show very high ratios. This indicates that a significant portion of passengers on these specific routes opt for First Class, even if the overall journey volume might not be as high as the busiest routes.
*   **High Value per Journey:** These routes often cater to business travelers or those willing to pay a premium for comfort and amenities, suggesting they are high-value segments for British Rail.
*   **Varying Preferences:** The preference for First Class is not uniform across all routes. While some major routes might have a large absolute number of First Class bookings, their ratio to Standard Class might be lower, indicating a broader passenger base.

**Strategic Implications:**

British Rail could leverage this insight by:
*   **Targeted Marketing:** Focusing marketing efforts for First Class services on these specific high-preference routes.
*   **Premium Service Enhancement:** Investing in First Class amenities and service quality on these routes to reinforce their premium appeal and retain high-value customers.
*   **Pricing Strategy:** Analyzing pricing elasticities for First Class on these routes to optimize revenue further.

## Passenger usage Analysis
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Extract the hour from 'Time of Purchase'
df['Purchase Hour'] = pd.to_datetime(df['Time of Purchase']).dt.hour

# Calculate passenger volume (number of transactions) per hour
passenger_volume_by_hour = df.groupby('Purchase Hour').size().reset_index(name='passenger_volume')

# Sort by hour to ensure chronological order for plotting
passenger_volume_by_hour = passenger_volume_by_hour.sort_values('Purchase Hour')

print("Passenger Volume by Hour of the Day:")
display(passenger_volume_by_hour.head())

# Visualize passenger volume by hour of the day
plt.figure(figsize=(12, 6))
sns.barplot(x='Purchase Hour', y='passenger_volume', data=passenger_volume_by_hour, palette='Blues_d', hue='Purchase Hour', legend=False)
plt.title('Passenger Volume by Hour of the Day')
plt.xlabel('Hour of the Day (24-hour format)')
plt.ylabel('Number of Passengers (Transactions)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Passenger Volume by Hour of the Day Analysis

The bar plot above illustrates the distribution of passenger volume across different hours of the day, based on the 'Time of Purchase'.

**Key Observations:**

*   **Morning and Evening Peaks:** There are clear peak hours in the morning (e.g., around 9-10 AM) and in the evening (e.g., around 5-6 PM). These typically correspond to commuting times.
*   **Overnight Lull:** As expected, passenger volume is significantly lower during late-night and early-morning hours (e.g., 1 AM to 5 AM).
*   **Specific Peak Hour:** The chart will visually highlight the hour with the highest number of transactions, indicating the busiest travel period for the network.

**Strategic Implications:**

Understanding peak travel hours is crucial for:
*   **Resource Allocation:** British Rail can optimize staff deployment, train frequency, and platform management during these busy periods.
*   **Marketing and Pricing:** Targeted promotions or dynamic pricing strategies could be implemented for off-peak hours to spread demand, or premium pricing could be considered for peak times.
*   **Infrastructure Management:** Maintenance and upgrade works can be scheduled during off-peak hours to minimize disruption to the largest number of passengers.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Extract month and year for grouping from the original df
df['Purchase Month'] = df['Date of Purchase'].dt.to_period('M')

# Calculate monthly passenger volume (count of transactions)
monthly_passenger_volume = df.groupby('Purchase Month').size().reset_index(name='passenger_volume')
monthly_passenger_volume['Purchase Month'] = monthly_passenger_volume['Purchase Month'].astype(str)

print("Monthly Passenger Volume:")
display(monthly_passenger_volume)

# Visualize monthly passenger volume
plt.figure(figsize=(12, 6))
sns.lineplot(x='Purchase Month', y='passenger_volume', data=monthly_passenger_volume, marker='o', color='#17BECF') # Cyan/Blue for volume
plt.title('Monthly Passenger Journey Trend')
plt.xlabel('Month of Purchase')
plt.ylabel('Number of Passengers (Transactions)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Monthly Passenger Journey Trend Analysis

The line plot above illustrates the monthly trend of passenger journeys based on the number of transactions.

**Key Observations:**

*   **Significant Increase in January 2024:** There is a very sharp increase in passenger volume from December 2023 to January 2024, similar to the revenue trend. This indicates a general surge in activity after the new year.
*   **Fluctuating Stability (January to April 2024):** After the initial jump, the passenger volume shows some monthly fluctuations but generally remains at a high level. There's a slight dip in February, followed by an increase in March, and then another dip in April.
*   **Overall Trend:** The overall trend from January to April suggests a period of relatively stable passenger volume, with some month-to-month variability. The initial data for December is much lower, making January the month with the highest observed passenger volume so far.

**Strategic Implications:**

Understanding this monthly trend is crucial for operational planning, resource allocation, and marketing efforts. The significant increase in January could be due to new year travel, promotions, or changes in service. Monitoring these trends over a longer period would provide more insights into seasonal patterns and growth.
"""

# Calculate the distribution of 'Ticket Class'
ticket_class_distribution = df['Ticket Class'].value_counts().reset_index()
ticket_class_distribution.columns = ['Ticket Class', 'Count']

print("Distribution of Ticket Class:")
display(ticket_class_distribution)

# Create a pie chart for Ticket Class distribution
plt.figure(figsize=(8, 8))
plt.pie(ticket_class_distribution['Count'], labels=ticket_class_distribution['Ticket Class'], autopct='%1.1f%%', startangle=90, colors=['#ADD8E6', '#1F77B4']) # Standard then First Class
plt.title('Distribution of Ticket Class')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the distribution of 'Ticket Type'
ticket_type_distribution = df['Ticket Type'].value_counts().reset_index()
ticket_type_distribution.columns = ['Ticket Type', 'Count']

print("\nDistribution of Ticket Type:")
display(ticket_type_distribution)

# Create a pie chart for Ticket Type distribution
plt.figure(figsize=(8, 8))
plt.pie(ticket_type_distribution['Count'], labels=ticket_type_distribution['Ticket Type'], autopct='%1.1f%%', startangle=90, colors=['#1F77B4', '#FF7F0E', '#FFEA00']) # Blue for Advance, Orange for Off-Peak, Yellow for Anytime
plt.title('Distribution of Ticket Type')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

"""#### Analysis of Ticket Class and Ticket Type Distribution

The pie charts above illustrate the distribution of 'Ticket Class' and 'Ticket Type' in the dataset.

**Key Observations - Ticket Class:**
*   **Standard Class Dominance:** The 'Standard Class' is overwhelmingly the most common ticket class, accounting for the vast majority of bookings.
*   **First Class as a Niche:** 'First Class' tickets represent a much smaller proportion of the total tickets, consistent with their premium nature and higher price point.

**Key Observations - Ticket Type:**
*   **E-Ticket Prevalence:** The 'E-Ticket' type is the most common, indicating a widespread adoption of digital ticketing.
*   **Physical Tickets in Minority:** 'Paper Ticket' and 'Mobile Ticket' represent smaller portions, suggesting that while still in use, they are less preferred or less widely available than E-Tickets.

**Strategic Implications:**

*   **Focus on Standard Class:** Given the high volume of Standard Class bookings, British Rail should prioritize optimizing services, pricing, and capacity for this segment to maintain customer satisfaction and revenue.
*   **Digital Transformation:** The dominance of E-Tickets reinforces the need for robust digital infrastructure and user-friendly online booking systems.
*   **Targeted First Class Strategy:** For 'First Class', the focus should remain on delivering premium experiences and targeted marketing to maintain its value proposition, rather than sheer volume.
"""

display(df.head(5))

print("Unique Payment Methods:")
display(df['Payment Method'].unique())

payment_method_distribution = df['Payment Method'].value_counts().reset_index()
payment_method_distribution.columns = ['Payment Method', 'Count']

print("\nDistribution of Payment Methods:")
display(payment_method_distribution)

plt.figure(figsize=(10, 6))
sns.barplot(x='Payment Method', y='Count', data=payment_method_distribution, palette={'Credit Card': '#1F77B4', 'Contactless': '#FF7F0E', 'Debit Card': '#FFEA00'}, hue='Payment Method', legend=False)
plt.title('Distribution of Payment Methods')
plt.xlabel('Payment Method')
plt.ylabel('Number of Transactions')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""#### Analysis of Payment Method Distribution

The bar chart above illustrates the distribution of different payment methods used for transactions.

**Key Observations:**
*   **Credit Card Dominance:** 'Credit Card' is the most frequently used payment method.
*   **Contactless and Debit Card Usage:** 'Contactless' and 'Debit Card' are also popular, following Credit Card in usage.

**Strategic Implications:**
*   **Payment Infrastructure:** The high usage of credit and contactless payments suggests the importance of robust and efficient systems for these transaction types.
*   **Customer Preferences:** Understanding these preferences can help in optimizing payment options and potentially targeting promotions or services related to specific payment methods.
"""